### ISSUE TITLE
Aidl not found, please install it

### ISSUE THREAD

**Issue by arun-arunisto** [kengoon/FlaskAndroid#1]
Error shows that Aidl not found please install it when i try to run the command buildozer -v android debug
but i already installed it
iam working on ubuntu please help me to sort this out

**Comment by kengoon** [comment]
@arun-arunisto run `sudo apt install aidl`

**Comment by kengoon** [comment]
or google how to install it

**Comment by arun-arunisto** [comment]
Actually i installed it but it still give me same issue

**Comment by kengoon** [comment]
take the issue to the kivy team
